add participants count to column in batch overview
scaffold-eth/buidlguidl-v3 pull request #118
Opened 2024-11-05 16:45 UTC by phipsae

Hey Carlos,

I just made a small adjustment by adding the participants count next to the graduates count, so we can get a better sense of how many started and how many completed successfully (in our opinion).

<img width="1337" alt="Screenshot 2024-11-05 at 13 42 46" src="https://github.com/user-attachments/assets/dcdec6c1-5375-495d-b0d5-bf13ade41fd6">

Best, Philip

2024-11-06 10:36 UTC, carletex commented on packages/react-app/pages/admin/batches.jsx
> +  }, [batches, serverUrl]);
Damn, this nested loop is ugly haha

We are also making 3 requests to the server to render this page, which doesn't make sense. 

Let's update the backend as needed so we don't need to do this. We could:

- Extend the /batches endpoint so it comes back with the count calculations
or
- Create a new `/batches/stats` route that includes this data

So we'll only need to do 1 request. Also will be helpful here https://github.com/BuidlGuidl/buidlguidl.com/pull/54#discussion_r1830737984

2024-11-06 10:37 UTC, carletex requested changes
Thanks @phipsae !

Added a review comment

2024-11-20 05:56 UTC, phipsae commented
Hey Carlos, 

I changed the /batches route so that it gives you the totalParicipants and graduates count for every batch. 
Pls let me know if I should make any adjustments.

Thank you!

2024-11-20 16:54 UTC, carletex approved these changes
This looks great. Thanks @phipsae !!

2024-11-20 17:07 UTC, merged